max_articles = 50
max_articles_for_search = 200
description_max_words = 150
feed_data_output_path = "./content/data/feedData.json"
item_data_output_path = "./content/data/itemData.json"
base_url = "https://feed-me-feeds.netlify.app/"

[categorization]
enabled = true

[feeds.bcantrill]
url = "https://bcantrill.dtrace.org/index.xml"
author = "Bryan Cantrill"
tier = "like"

[feeds.charitywtf]
tier = "new"

[feeds.cliffle]
tier = "love"

[feeds.corydoctorow]
url = "https://pluralistic.net/feed"
author = "Cory Doctorow"
tier = "love"

[feeds.danluu]
tier = "new"

[feeds.fasterthanlime]
tier = "love"

[feeds.hackernews]
tier = "new"

[feeds.inside_rust]
tier = "like"

[feeds.jvns]
tier = "love"

[feeds.lexilambda]
tier = "new"

[feeds.matklad]
tier = "like"

[feeds.noboilerplate]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCUMwY9iS8oMyWDYIe6_RmoA"
author = "Tris 0atman"
tier = "like"

[feeds.rust_official]
tier = "like"

[feeds.simonwillison]
tier = "like"

[feeds.smallcultfollowing]
tier = "new"

[feeds.withoutboats]
tier = "new"

[feeds.xeiaso]
tier = "like"
