base_url = 'https://feed-me-feeds.netlify.app/'
max_articles = 50
description_max_words = 150
feed_data_output_path = "./content/data/feedData.json"
item_data_output_path = "./content/data/itemData.json"

[feeds.smallcultfollowing]
url = "https://smallcultfollowing.com/babysteps//atom.xml"
author = "Niko Matsakis"
tier = "like"

[feeds.charitywtf]
url = "https://charity.wtf/feed/"
author = "Charity Majors"
tier = "like"

[feeds.hackernews]
url = "https://hnrss.org/newest?points=100"
author = "Hacker News"
tier = "new"

[feeds.jvns]
url = "https://jvns.ca/atom.xml"
author = "Julia Evans"
tier = "love"

[feeds.dzone_devops]
url = "https://feeds.dzone.com/devops-and-cicd"
author = "DZone"
tier = "new"

[feeds.lexilambda]
url = "https://lexi-lambda.github.io/feeds/all.atom.xml"
author = "Lexi Lambda"
tier = "like"

[feeds.chriskrycho]
url = "https://v5.chriskrycho.com/feed.xml"
author = "Chris Krycho"
tier = "like"


[feeds.atlassian_devops]
url = "https://www.atlassian.com/blog/devops/feed"
author = "Atlassian"
tier = "new"

[feeds.devopscom]
url = "https://devops.com/feed"
author = "DevOps.com"
tier = "new"

[feeds.inside_rust]
url = "https://blog.rust-lang.org/inside-rust/feed.xml"
author = "Inside Rust"
tier = "like"

[feeds.hazelweakly]
url = "https://hazelweakly.me/atom.xml"
author = "Hazel Weakly"
tier = "new"

[feeds.withoutboats]
url = "https://without.boats/index.xml"
author = "Without Boats"
tier = "like"

[feeds.theregister]
url = "https://www.theregister.com/headlines.atom"
author = "The Register"
tier = "new"

[feeds.cliffle]
url = "https://cliffle.com/rss.xml"
author = "Cliff Biffle"
tier = "love"

[feeds.bcantrill]
url = "https://bcantrill.dtrace.org/rss"
author = "Bryan Cantrill"
tier = "like"

[feeds.danluu]
url = "https://danluu.com/atom.xml"
author = "Dan Luu"
tier = "new"

[feeds.noboilerplate]
url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCUMwY9iS8oMyWDYIe6_RmoA"
author = "Tris 0atman"
tier = "like"

[feeds.fasterthanlime]
url = "https://fasterthanli.me/index.xml"
author = "fasterthanlime"
tier = "love"

[feeds.itrevolution]
url = "https://itrevolution.com/devops-blog/feed/"
author = "IT Revolution"
tier = "new"

[feeds.xeiaso]
url = "https://xeiaso.net/blog.rss"
author = "Xe Iaso"
tier = "like"

[feeds.noracodes]
url = "https://nora.codes/index.xml"
author = "Nora Tindall"
tier = "like"

[feeds.matklad]
url = "https://matklad.github.io/feed.xml"
author = "Alex Kladov"
tier = "like"

[feeds.rust_official]
url = "https://blog.rust-lang.org/feed.xml"
author = "Rust"
tier = "like"

[feeds.simonwillison]
url = "https://simonwillison.net/atom/everything/"
author = "Simon Willison"
tier = "like"
