on:
  schedule:
    # At minute 23 past hour 5, 9, 14, 18, and 22 (UTC)
    # Optimized for being up to date at certain key times during
    # the day (waking up, lunch break, finishing work). Off-hour
    # minute chosen to reduce risk of job getting delayed due to
    # load.
    - cron: "23 5,9,14,18,22 * * *"
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  fetch_feeds:
    name: Fetch feed content
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Install spacefeeder
        shell: bash
        # TODO: Don't blindly use latest version, build new if necessary or pin to a version
        run: "curl --proto '=https' --tlsv1.2 -LsSf https://github.com/wonderfulspam/feed.me/releases/latest/download/spacefeeder-installer.sh | sh"
      - name: Fetch feed content
        run: "mkdir -p content/data && spacefeeder fetch"
      - name: Upload feed content
        uses: actions/upload-artifact@v4
        with:
          name: feed-content
          path: content/data/
  build_site:
    name: Build site HTML
    needs: fetch_feeds
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Fetch feed content
        uses: actions/download-artifact@v4
        with:
          name: feed-content
          path: content/data/
      - name: Build site
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
      - name: Upload HTML content
        uses: actions/upload-artifact@v4
        with:
          name: html-content
          path: public
  publish_site:
    name: Publish HTML to Netlify
    needs: build_site
    runs-on: "ubuntu-latest"
    if: github.event_name != 'pull_request'
    steps:
      - name: Fetch HTML
        uses: actions/download-artifact@v4
        with:
          name: html-content
          path: public
      - name: Publish
        env:
          NETLIFY_DEPLOY_TOKEN: ${{ secrets.NETLIFY_DEPLOY_TOKEN }}
          SITE_URL: "feed-me-feeds.netlify.com"
        run: |
          zip -r site.zip public
          curl -H "Content-Type: application/zip" \
             -H "Authorization: Bearer $NETLIFY_DEPLOY_TOKEN" \
             --data-binary "@site.zip" \
             "https://api.netlify.com/api/v1/sites/${SITE_URL}/deploys"
          rm site.zip
